#!/usr/bin/env bash
#
# Usage:
#  build [options]
#
# This program builds the cyverse/irods image tagged with `new`.

set -o errexit -o nounset -o pipefail

BASE_DIR="$(dirname "$(realpath --canonicalize-existing "$0")")"
readonly BASE_DIR

main() {
	docker build --tag cyverse/irods:new "$BASE_DIR"
}

main "$@"
