---
name: test and publish
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: build base image
        run: docker buildx build --tag cyverse/irods:latest .

      # - name: build base image
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: false
      #     tags: cyverse/irods:latest

      - name: where am i
        run: pwd

      - name: what is here
        run: ls -a

      - name: build test image
        run: docker buildx build test

      # - name: publish base image
      #   if: ${{ github.ref_name == 'main' }}
      #   run: ./build --push
