---
name: Test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build base image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: cyverse/irods:4.2.12

      # - name: build test image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: test
      #     push: false
      #     tags: test:latest
