---
name: Test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build base image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: cyverse/irods:latest

      - name: build test image
        uses: docker/build-push-action@v4
        with:
          context: "{{ defaultContext }}:test"
          push: false
          tags: test:latest

      # - name: publish base image
      #   if: ${{ github.ref_name == 'main' }}
      #   run: ./build --push
