---
name: test and publish
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: build base image
        run: "${{ github.repository }}/build"

      - name: build test image
        run: docker buildx build "${{ github.repository }}"/test

      - name: log into Docker Hub
        if: ${{ github.ref_name == 'main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: publish base image
        if: ${{ github.ref_name == 'main' }}
        run: "${{ github.repository }}/publish"
