---
name: test and publish
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: build base image
        run: docker buildx build --tag cyverse/irods:latest "${{ github.repository }}"

      - name: build test image
        run: docker buildx build "${{ github.repository }}"/test

      # - name: publish base image
      #   if: ${{ github.ref_name == 'main' }}
      #   run: ./build --push
